name: nif_validator
version: 1.0.2
description: |
  Este pacote Dart fornece uma ferramenta
  para validar NIFs (Número de Identificação Fiscal)
  em Angola através do endpoint do SEPE.
repository: https://github.com/paulinofonsecas/nif_validator
topics:
  - bi
  - nif
  - angola
  - validator

environment:
  sdk: ^3.3.2

dependencies:
  dio: ^5.4.3+1

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
